backend_tv/mc.cpp
tests/arm-tv/instructions/UXTB-1.asminput.ll
tests/arm-tv/instructions/UXTB-1.asminput.s

Added `UXTH` support and fixed `UXTB` crash.

Added UXTH support

---

backend_tv/lifter.cpp
tests/arm-tv/pointers/STRWpre.asminput.ll
tests/arm-tv/pointers/STRWpre.asminput.s
tests/arm-tv/pointers/STRXpre.asminput.ll
tests/arm-tv/pointers/STRXpre.asminput.s

`STRWpre` is debilitatingly slow for some reason, but `STRXpre` works quickly.

Added STRXpre and STRWpre

---

backend_tv/adjust_src.cpp
backend_tv/lifter.cpp
tests/arm-tv/globals/global-test-100.aarch64.ll
tests/arm-tv/vectors/add_v8_i8.aarch64.ll

Please look at the commit messages of individual commits.
Test status same as before these changes except for two additional tests part of the commit which also pass.

Added RegFile for SIMD&FP registers and instruction support for LDRDui, STRDui and ADDv8i8

---

backend_tv/lifter.cpp
tests/arm-tv/vectors/not/test_8_8-0.aarch64.ll
tests/arm-tv/vectors/not/test_8_8-1.aarch64.ll
tests/arm-tv/vectors/not/test_8_8-2.aarch64.ll
tests/arm-tv/vectors/not/test_8_8-3.aarch64.ll

Added NOTv8i8
Added 4 passing tests from 1834 zip file

Added NOTv8i8

---

backend_tv/lifter.cpp
tests/arm-tv/globals/global-test-105.aarch64.ll

Add else if case on getBitWidth
Merged some cases together in STR
Fixed LDRBBui when Expr is involved
Added test case to check for this bug
clang-formatted

Fixing LDRBBui

---

backend_tv/lifter.cpp
tests/arm-tv/mem-ops/LDRWroX.aarch64.ll

Added support and test for LDRWroX

---

backend_tv/lifter.cpp
tests/arm-tv/mem-ops/LDRXroX.aarch64.ll
tests/arm-tv/mem-ops/STRWroX.aarch64.ll
tests/arm-tv/mem-ops/STRXroX.aarch64.ll

Added support and tests for LDRXroX, STRWroX and STRXroX
clang-formatted

Added support and tests for LDRXroX, STRWroX and STRXroX

---

backend_tv/lifter.cpp

Added comments explaining the two global creating loops

Added comments

---

backend_tv/lifter.cpp
tests/arm-tv/mem-ops/LDURBBi.aarch64.ll
tests/arm-tv/mem-ops/LDURBi.aarch64.ll
tests/arm-tv/mem-ops/LDURDi.aarch64.ll
tests/arm-tv/mem-ops/LDURHHi.aarch64.ll
tests/arm-tv/mem-ops/LDURHi.aarch64.ll
tests/arm-tv/mem-ops/LDURQi.aarch64.ll
tests/arm-tv/mem-ops/LDURSi.aarch64.ll
tests/arm-tv/mem-ops/LDURWi.aarch64.ll
tests/arm-tv/mem-ops/LDURXi.aarch64.ll

Added support and tests for ldur (LDURWi and LDURXi)
Added support and tests for ldurh (LDURHHi)
Added support and tests for ldurb (LDURBBi)
Added support and tests for ldur (SIMD&FP regs) (LDURBi, LDURHi, LDURSi, LDURDi, LDURQi)

Added support for all ldur (unsigned)

---

backend_tv/lifter.cpp
tests/arm-tv/mem-ops/SMOVvi16to64.aarch64.ll
tests/arm-tv/mem-ops/SMOVvi32to64.aarch64.ll
tests/arm-tv/mem-ops/SMOVvi8to32.aarch64.ll
tests/arm-tv/mem-ops/SMOVvi8to64.aarch64.ll

Added support for SMOV
clang-formatted

Added support for SMOV

---

backend_tv/lifter.cpp
tests/arm-tv/vectors/dup/DUPi64.aarch64.ll
tests/arm-tv/vectors/xtn/XTNv16i8.aarch64.ll
tests/arm-tv/vectors/xtn/XTNv4i32.aarch64.ll
tests/arm-tv/vectors/xtn/XTNv8i16.aarch64.ll
tests/arm-tv/vectors/xtn/XTNv8i8.aarch64.ll

Completed support for XTN by adding support for XTN2.
Added tests.
Only 1 test present for XTN, 2 more required to cover all variants.

Completed support for XTN (added XTN2)

---

backend_tv/lifter.cpp
tests/arm-tv/mem-ops/LDRHHpost.aarch64.ll
tests/arm-tv/mem-ops/LDRHHpre.aarch64.ll
tests/arm-tv/mem-ops/STRHHpost.aarch64.ll
tests/arm-tv/mem-ops/STRHHpre.aarch64.ll

Added support for LDRH (imm) (pre/post index) and STRH (imm) (pre/post index)
Merged existing STR pre/post index code

Added support for LDRH (imm) (pre/post index) and STRH (imm) (pre/post index)

---

backend_tv/lifter.cpp
tests/arm-tv/mem-ops/LDRBBpost.aarch64.ll
tests/arm-tv/mem-ops/LDRBBpre.aarch64.ll
tests/arm-tv/mem-ops/STRBBpost.aarch64.ll
tests/arm-tv/mem-ops/STRBBpre.aarch64.ll

Add support for LDRB (imm) (pre/post index) and STRB (imm) (pre/post index)

Add support for LDRB (imm) (pre/post index) and STRB (imm) (pre/post index)

---

backend_tv/lifter.cpp
tests/arm-tv/mem-ops/STURBBi.aarch64.ll
tests/arm-tv/mem-ops/STURDi.aarch64.ll
tests/arm-tv/mem-ops/STURHHi.aarch64.ll
tests/arm-tv/mem-ops/STURHi.aarch64.ll
tests/arm-tv/mem-ops/STURQi.aarch64.ll
tests/arm-tv/mem-ops/STURSi.aarch64.ll

Complete support for STUR (general purpose and SIMD&FP regs)
Combined code with STR (unsigned offset)

Complete support for STUR (general purpose and SIMD&FP regs)

---

backend_tv/lifter.cpp
tests/arm-tv/mem-ops/LDRSBWpost.aarch64.ll
tests/arm-tv/mem-ops/LDRSBWpre.aarch64.ll
tests/arm-tv/mem-ops/LDRSBXpost.aarch64.ll
tests/arm-tv/mem-ops/LDRSBXpre.aarch64.ll
tests/arm-tv/mem-ops/LDRSHWpost.aarch64.ll
tests/arm-tv/mem-ops/LDRSHWpre.aarch64.ll
tests/arm-tv/mem-ops/LDRSHXpost.aarch64.ll
tests/arm-tv/mem-ops/LDRSHXpre.aarch64.ll
tests/arm-tv/mem-ops/LDRSWpre.aarch64.ll

Added support for LDRSW, LDRSB and LDRSH (pre/post index)

Added support for LDRSW, LDRSB and LDRSH (pre/post index)

---

backend_tv/lifter.cpp
tests/arm-tv/mem-ops/LDURSBWi.aarch64.ll
tests/arm-tv/mem-ops/LDURSBXi.aarch64.ll
tests/arm-tv/mem-ops/LDURSHWi.aarch64.ll
tests/arm-tv/mem-ops/LDURSHXi.aarch64.ll
tests/arm-tv/mem-ops/LDURSWi.aarch64.ll

Add support for LDURSB, LDURSH and LDURSW
Corrected sign extension of offset for LDUR. No bugs found becuase of this yet.

Add support for LDURSB, LDURSH and LDURSW

---

backend_tv/lifter.cpp
tests/arm-tv/vectors/umlal/UMLALv2i32_v2i64.aarch64.ll
tests/arm-tv/vectors/umlal/UMLALv4i16_v4i32.aarch64.ll
tests/arm-tv/vectors/umlal/UMLALv8i16_v4i32.aarch64.ll
tests/arm-tv/vectors/umlal/UMLALv8i8_v8i16.aarch64.ll

Added support for `UMLAL (vector)`
Fixed a lot of int to unsigned int narrowing warnings.

Added support for `UMLAL (vector)`

---

backend_tv/lifter.cpp
tests/arm-tv/mem-ops/LDPSWi.aarch64.ll
tests/arm-tv/vectors/ssubl/SSUBLv4i16_v4i32.aarch64.ll

Added support for `LDPSW (Signed Offset)`
Added missing test in SSUBLv4i16_v4i32.aarch64.ll
Fixed a comparison between int and unsigned.

Added support for `LDPSW (Signed Offset)`

---

backend_tv/lifter.cpp
tests/arm-tv/mem-ops/LD4/LD4Fourv16b.aarch64.ll
tests/arm-tv/mem-ops/LD4/LD4Fourv2d.aarch64.ll
tests/arm-tv/mem-ops/LD4/LD4Fourv4h.aarch64.ll
tests/arm-tv/mem-ops/LD4/LD4Fourv8b.aarch64.ll
tests/arm-tv/mem-ops/LD4/LD4Fourv8h.aarch64.ll

Added support for `LD4 (multiple structure) (no offset)`
Modified decodeRegSet for D register sets
Tests for `LD4Fourv2s` and `LD4Fourv4s` timeout.

Added support for `LD4 (multiple structure) (no offset)`

---

backend_tv/lifter.cpp
tests/arm-tv/mem-ops/LD4/LD4Fourv16b_POST.aarch64.ll
tests/arm-tv/mem-ops/LD4/LD4Fourv4s_POST.aarch64.ll
tests/arm-tv/mem-ops/LD4/LD4Fourv8h_POST.aarch64.ll

Added support for `LD4 (multiple structure) (post-index)`

Added support for `LD4 (multiple structure) (post-index)`

---

backend_tv/lifter.cpp
tests/arm-tv/vectors/sabd/SABDv16i8.aarch64.ll
tests/arm-tv/vectors/sabd/SABDv2i32.aarch64.ll
tests/arm-tv/vectors/sabd/SABDv4i16.aarch64.ll
tests/arm-tv/vectors/sabd/SABDv4i32.aarch64.ll
tests/arm-tv/vectors/sabd/SABDv8i16.aarch64.ll
tests/arm-tv/vectors/sabd/SABDv8i8.aarch64.ll

Added support for `SABD`

---

backend_tv/lifter.cpp
tests/arm-tv/fp/fdiv/FDIVDrr.aarch64.ll
tests/arm-tv/fp/fdiv/FDIVSrr.aarch64.ll
tests/arm-tv/fp/fneg/FNEGDr.aarch64.ll
tests/arm-tv/fp/fqsrt/FSQRTDr.aarch64.ll
tests/arm-tv/fp/fqsrt/FSQRTSr.aarch64.ll

Added support for `FDIV (scalar)`, `FSQRT (scalar)` and `FNEG (scalar)`

Added support for `FDIV (scalar)`, `FSQRT (scalar)` and `FNEG (scalar)`

---

backend_tv/lifter.cpp
tests/arm-tv/misc/SUBXrx64.aarch64.ll

Added support for `SUBXrx64`

---

backend_tv/lifter.cpp
tests/arm-tv/fp/frintm/FRINTMDr.aarch64.ll
tests/arm-tv/fp/frintm/FRINTMSr.aarch64.ll
tests/arm-tv/fp/frintp/FRINTPDr.aarch64.ll

Added support for `FRINTM` and `FRINTP`

Added support for `FRINTM` and `FRINTP`

---

backend_tv/lifter.cpp
tests/arm-tv/vectors/sli/SLIv16i8_shift.aarch64.ll
tests/arm-tv/vectors/sli/SLIv2i32_shift.aarch64.ll
tests/arm-tv/vectors/sli/SLIv2i64_shift.aarch64.ll
tests/arm-tv/vectors/sli/SLIv4i16_shift.aarch64.ll
tests/arm-tv/vectors/sli/SLIv4i32_shift.aarch64.ll
tests/arm-tv/vectors/sli/SLIv8i16_shift.aarch64.ll
tests/arm-tv/vectors/sli/SLIv8i8_shift.aarch64.ll
tests/arm-tv/vectors/sri/SRIv16i8_shift.aarch64.ll
tests/arm-tv/vectors/sri/SRIv2i32_shift.aarch64.ll
tests/arm-tv/vectors/sri/SRIv2i64_shift.aarch64.ll
tests/arm-tv/vectors/sri/SRIv4i16_shift.aarch64.ll
tests/arm-tv/vectors/sri/SRIv4i32_shift.aarch64.ll
tests/arm-tv/vectors/sri/SRIv8i16_shift.aarch64.ll
tests/arm-tv/vectors/sri/SRIv8i8_shift.aarch64.ll

Added support for `SLI` and `SRI`

Added support for `SLI` and `SRI`

---

backend_tv/adjust_src.cpp
backend_tv/lifter.h
tests/arm-tv/unhandled/dynamic-rounding.aarch64.ll

Rejecting LLVM IR that uses dynamic rounding mode.

Rejecting LLVM IR that uses dynamic rounding mode.

---

backend_tv/aslp/CMakeLists.txt

this will bring in recent changes to aslp-cpp, including some fixes for warnings.

aslp: unpin fetch of aslp-cpp repository

---

backend_tv/riscv2llvm_insns.cpp
tests/riscv-tv/branch/tricky.riscv.ll
tests/riscv-tv/branch/tricky2.riscv.ll
tests/riscv-tv/branch/tricky3.riscv.ll
tests/riscv-tv/branch/tricky4.riscv.ll
tests/riscv-tv/extensions/b/orc_b.riscv.ll
tests/riscv-tv/extensions/b/orc_b2.riscv.ll
tests/riscv-tv/extensions/b/roriw.riscv.ll
tests/riscv-tv/extensions/b/rorw.riscv.ll

Please check that this is a valid fix for the crash

RISCV-TV: Finish B extension for now + fix crash for
