llvm_util/llvm2alive.cpp
This PR ports [b280fa03f3567a3832fac304921846ac77219f5d](https://github.com/AliveToolkit/alive2/commit/b280fa03f3567a3832fac304921846ac77219f5d)  commit from the main repo to fix the build with the latest LLVM
=> Port commit to fix build with latest LLVM

backend_tv/lifter.cpp, tests/arm-tv/globals/global-test-101.aarch64.ll, tests/arm-tv/globals/global-test-102.aarch64.ll, tests/arm-tv/globals/global-test-103.aarch64.ll, tests/arm-tv/globals/global-test-104.aarch64.ll
Added code to create globals from LLVM source module if not created already due to absence in Machine Function (Do not remove Machine Function global creation. It has sizes along with globals whereas LLVM may not) Added few tests for globals not found in Machine Function
=> Handled globals not in Machine Function

backend_tv/lifter.cpp, tests/arm-tv/vectors/popcnt/test_16_8.aarch64.ll, tests/arm-tv/vectors/popcnt/test_8_8.aarch64.ll
Created a function to create an LLVM ConstantVector out of a vector of Constants
Created a function to create a mask value based on type of value and bitwidth
Used this function is LLVM shift creators
Added support for CNTv8i8 CNTv16i8
Added test cases for popcnt
clang formatted
=> Added support for POPCNT and created masked versions of shifts

backend_tv/lifter.cpp, tests/arm-tv/globals/global-test-107.aarch64.ll, tests/arm-tv/mem-ops/LDRWroWwithExtendShift.aarch64.ll, tests/arm-tv/mem-ops/LDRXroWwithExtendShift.aarch64.ll, tests/arm-tv/mem-ops/LDRXroXwithShift.aarch64.ll, tests/arm-tv/mem-ops/STRWroWwithExtendShift.aarch64.ll, tests/arm-tv/mem-ops/STRWroXwithShift.aarch64.ll, tests/arm-tv/mem-ops/STRXroWwithExtendShift.aarch64.ll, tests/arm-tv/mem-ops/STRXroXwithShift.aarch64.ll
In LDR cases, determine whether to load the global depending on relocation specifiers. Added a fix to do this.
Modified getExprVar to return a storePtr boolean determining whether to store the global in register or load the value from it first.
Added support for LDRWroW, STRWroW, LDRXroW and STRXroW
Added helper function extendAndShiftValue to extend and shift value depending on the extend type and shift amount and used it.
Modified getParamsLoadReg and getParamsStoreReg
clang-formatted using  version 18
=> Fixed Relocation specifier issue and Added support for more *ro* style LDR instructions

backend_tv/lifter.cpp, tests/arm-tv/mem-ops/LDRBBroWwithExtend.aarch64.ll, tests/arm-tv/mem-ops/LDRBBroX.aarch64.ll, tests/arm-tv/mem-ops/LDRHHroWwithExtendShift.aarch64.ll, tests/arm-tv/mem-ops/LDRHHroXwithShift.aarch64.ll, tests/arm-tv/mem-ops/STRBBroWwithExtend.aarch64.ll, tests/arm-tv/mem-ops/STRBBroX.aarch64.ll, tests/arm-tv/mem-ops/STRHHroWwithExtendShift.aarch64.ll, tests/arm-tv/mem-ops/STRHHroX.aarch64.ll
Added support for and tests for LDRH (LDRHHroW and LDRHHBroX)
Added support for and tests for STRH (STRHHroW and STHHBroX)
Added support for and tests for STRB (STRBBroW and STRBBroX)
Added support for and tests for LDRB (LDRBBroW and LDRBBroX)
Fixed a bug wherein the global created had the wrong type. One of the tests included in this commit caught it.
Cleaned up extendAndShiftValue so isSigned becomes more intuitive.
clang-formatted using clang-17
=> Added support for strb, ldrb, strh and ldrh

backend_tv/lifter.cpp
Created new helper createPtrToInt
Improved comments
Cleaned up LDR (Immediate) Expr case using PrtToInt instruction instead of storing global ptr value (More intuitive this way).
Set global value alignment based on source IR global
=> Fixed  tests/arm-tv/align/1.aarch64.ll and cleanup

backend_tv/lifter.cpp
Removed a duplicate function
Overrode emitValueToAlignment function
Changed Value part of the MCFunction::globals map from int64 to pair<uint64, uint64>
Setting default alignment to 16 bytes as was the case with fixed alignment
Now using alignment to creating globals for assembly provided globals too
=> Added alignment to assembly provided globals

backend_tv/lifter.cpp, tests/arm-tv/mem-ops/LD1i16.aarch64.ll, tests/arm-tv/mem-ops/LD1i32.aarch64.ll, tests/arm-tv/mem-ops/LD1i64.aarch64.ll, tests/arm-tv/mem-ops/LD1i8.aarch64.ll, tests/arm-tv/mem-ops/ST1i16.aarch64.ll, tests/arm-tv/mem-ops/ST1i32.aarch64.ll, tests/arm-tv/mem-ops/ST1i64.aarch64.ll, tests/arm-tv/mem-ops/ST1i8.aarch64.ll
Cleanup
Changed decodeLogicalImmediate to decodeBitMasks
Replaced all switch-case return statements with breaks.
Added support and tests for ld1 (single structure) (no offset) [LD1i8, LD1i16, LD1i32, LD1i64]
Added support and tests for st1 (single structure) (no offset) [ST1i8, ST1i16, ST1i32, ST1i64]
=> Added support for ld1 (single structure) (no offset) and st1 (single structure) (no offset)

backend_tv/lifter.cpp, tests/arm-tv/mem-ops/STRDroXwithShift.aarch64.ll
Add support for LDR[SD]ro[WX], STR[SD]ro[WX], LDRQroW and STRQroW
Lifted code for many of these tests are too big even on optimizing.
=> Add support for LDR[SD]ro[WX], STR[SD]ro[WX], LDRQroW and STRQroW

backend_tv/lifter.cpp, tests/arm-tv/mem-ops/LDPDi.aarch64.ll, tests/arm-tv/mem-ops/LDPWpre.aarch64.ll, tests/arm-tv/mem-ops/STPDpost.aarch64.ll, tests/arm-tv/mem-ops/STPDpre.aarch64.ll, tests/arm-tv/mem-ops/STPQpost.aarch64.ll, tests/arm-tv/mem-ops/STPQpre.aarch64.ll, tests/arm-tv/mem-ops/STPWpost.aarch64.ll, tests/arm-tv/mem-ops/STPWpre.aarch64.ll, tests/arm-tv/mem-ops/STPXpost.aarch64.ll
STP tested thoroughly. LDP (pre/post index) could use more testing. Tar ball tests time out.
=> Added support for LDP and STP (general purpose AND SIMD&FP reg) (signed offset, pre/post index)

backend_tv/lifter.cpp, tests/arm-tv/mem-ops/LDRSBWroW.aarch64.ll, tests/arm-tv/mem-ops/LDRSBWroX.aarch64.ll, tests/arm-tv/mem-ops/LDRSBXroX.aarch64.ll, tests/arm-tv/mem-ops/LDRSHWroW.aarch64.ll, tests/arm-tv/mem-ops/LDRSHWroX.aarch64.ll, tests/arm-tv/mem-ops/LDRSHXroW.aarch64.ll, tests/arm-tv/mem-ops/LDRSHXroX.aarch64.ll, tests/arm-tv/mem-ops/LDRSWroW.aarch64.ll, tests/arm-tv/mem-ops/LDRSWroX.aarch64.ll
Add support for `LDRSB (register)`, `LDRSH (register)`, and `LDRSW (register)`
=> Add support for `LDRSB (register)`, `LDRSH (register)`, and `LDRSW (register)`

backend_tv/lifter.cpp, tests/arm-tv/vectors/smlal/SMLALv2i32_v2i64.aarch64.ll, tests/arm-tv/vectors/smlal/SMLALv4i16_v4i32.aarch64.ll, tests/arm-tv/vectors/smlal/SMLALv8i16_v4i32.aarch64.ll, tests/arm-tv/vectors/smlal/SMLALv8i8_v8i16.aarch64.ll
Added support for `SMLAL (vector)`
Added commented code for `UMLAL (by element)` and `SMLAL (by element)` due to lack of tests and removed the initial incomplete commented code.
Fixed an int to unsigned int narrowing warning.
=> Added support for `SMLAL (vector)`

backend_tv/lifter.cpp, tests/arm-tv/vectors/smlsl/SMLSLv2i32_v2i64.aarch64.ll, tests/arm-tv/vectors/smlsl/SMLSLv4i16_v4i32.aarch64.ll, tests/arm-tv/vectors/smlsl/SMLSLv8i8_v8i16.aarch64.ll, tests/arm-tv/vectors/umlsl/UMLSLv2i32_v2i64.aarch64.ll, tests/arm-tv/vectors/umlsl/UMLSLv4i16_v4i32.aarch64.ll, tests/arm-tv/vectors/umlsl/UMLSLv8i8_v8i16.aarch64.ll
Added support for `UMLSL (vector)` and `SMLSL (vector)`
Added tests for half the variants
Added coommented code for `UMLSL (by element)` and `SMLSL (by element)` due to lack of tests without NEON intrinsics.
=> Added support for `UMLSL (vector)` and `SMLSL (vector)`

backend_tv/lifter.cpp
Completed support for LDR and STR
No tests in the tar ball for these but implementation is 100% correct since its other variants are well tested.
Desktop does not contain right version of clang-format so left it unformatted
=> Completed support for `LDR (register)` and `STR (register)`

backend_tv/lifter.cpp, tests/arm-tv/vectors/uaddl/UADDLv16i8_v8i16.aarch64.ll, tests/arm-tv/vectors/uaddl/UADDLv2i32_v2i64.aarch64.ll, tests/arm-tv/vectors/uaddl/UADDLv4i16_v4i32.aarch64.ll, tests/arm-tv/vectors/uaddl/UADDLv4i32_v2i64.aarch64.ll, tests/arm-tv/vectors/uaddl/UADDLv8i16_v4i32.aarch64.ll
Completed support for `UADDL` and `UADDL2`
Added an isUpper parameter to createVectorOp()
=> Completed support for `UADDL` and `UADDL2`

backend_tv/lifter.cpp, tests/arm-tv/vectors/fneg/FNEGv2f32.aarch64.ll, tests/arm-tv/vectors/fneg/FNEGv2f64.aarch64.ll, tests/arm-tv/vectors/fneg/FNEGv4f32.aarch64.ll
Added support for `FNEG (vector)`
Not added support for the half precision variants due to lack of tests
=> Added support for `FNEG (vector)`

backend_tv/lifter.cpp, tests/arm-tv/vectors/scvtf/SCVTFUWDri.aarch64.ll, tests/arm-tv/vectors/scvtf/SCVTFUWSri.aarch64.ll, tests/arm-tv/vectors/scvtf/SCVTFUXDri.aarch64.ll, tests/arm-tv/vectors/scvtf/SCVTFUXSri.aarch64.ll
Added support for `SCVTF (scalar, integer)`
Not added support for the half precision variants due to lack of tests
=> Added support for `SCVTF (scalar, integer)`

backend_tv/lifter.cpp, tests/arm-tv/vectors/ucvtf/UCVTFUWDri.aarch64.ll, tests/arm-tv/vectors/ucvtf/UCVTFUWSri.aarch64.ll, tests/arm-tv/vectors/ucvtf/UCVTFUXDri.aarch64.ll
Added support for `UCVTF (scalar, integer)`
Not added support for the half precision variants due to lack of tests
=> Added support for `UCVTF (scalar, integer)`

backend_tv/lifter.cpp, tests/arm-tv/vectors/ucvtf/UCVTFUWDri_2.aarch64.ll
Bug fix - Was converting to the incorrect floating point type. The type to be converted to depends on the destination register and not source.
Another incorrect implementation - readFromReg does a full-width read. Replaced it with readFromOperand
=> Bug fix - UCVTF

backend_tv/lifter.cpp, tests/arm-tv/mem-ops/LD2/LD2Twov16b.aarch64.ll, tests/arm-tv/mem-ops/LD2/LD2Twov16b_POST.aarch64.ll, tests/arm-tv/mem-ops/LD2/LD2Twov2d.aarch64.ll, tests/arm-tv/mem-ops/LD2/LD2Twov2d_POST.aarch64.ll, tests/arm-tv/mem-ops/LD2/LD2Twov2s.aarch64.ll, tests/arm-tv/mem-ops/LD2/LD2Twov4h.aarch64.ll, tests/arm-tv/mem-ops/LD2/LD2Twov4s.aarch64.ll, tests/arm-tv/mem-ops/LD2/LD2Twov4s_POST.aarch64.ll, tests/arm-tv/mem-ops/LD2/LD2Twov8b.aarch64.ll, tests/arm-tv/mem-ops/LD2/LD2Twov8h.aarch64.ll, tests/arm-tv/mem-ops/LD2/LD2Twov8h_POST.aarch64.ll
Added support for `LD1` and `LD2` `(multiple structure) (no offset AND post-index)`
=> Added support for `LD1` and `LD2` `(multiple structure) (no offset AND post-index)`

backend_tv/lifter.cpp, tests/arm-tv/fp/fcmp/FCMPESri.aarch64.ll, tests/arm-tv/vectors/fcvtzs/FCVTZSv1i32.aarch64.ll, tests/arm-tv/vectors/fcvtzs/FCVTZSv1i64.aarch64.ll, tests/arm-tv/vectors/scvtf/SCVTFv1i32.aarch64.ll, tests/arm-tv/vectors/scvtf/SCVTFv1i64.aarch64.ll
Added support for `FCVTZS (scalar, integer)`
Reimplemented `FCVT` and `FCVTZU (scalar, integer)` to explicitly convert to floating-point
Added tests for some unsupported instructions to be worked on next
=> Added support for `FCVTZS (scalar, integer)`

backend_tv/lifter.cpp, tests/arm-tv/vectors/fmov/FMOVv2f32_ns.aarch64.ll, tests/arm-tv/vectors/fmov/FMOVv2f64_ns.aarch64.ll, tests/arm-tv/vectors/fmov/FMOVv4f32_ns.aarch64.ll
Added support for `FMOV (vector, immediate)`
Not supporting half precision variants due to lack of tests
=> Added support for `FMOV (vector, immediate)`

backend_tv/lifter.cpp, tests/arm-tv/fp/fcmp/FCMPEDrr.aarch64.ll, tests/arm-tv/vectors/fmsub/FMSUBSrrr.aarch64.ll, tests/arm-tv/vectors/fmul/FMULv1i32_indexed.aarch64.ll, tests/arm-tv/vectors/fnmadd/FNMADDDrrr.aarch64.ll, tests/arm-tv/vectors/fnmul/FNMULDrr.aarch64.ll, tests/arm-tv/vectors/fnmul/FNMULSrr.aarch64.ll
Added support for FMUL (by element) (scalar, single-precision and double-precision), FNMUL (scalar), FNMADD, FNMSUB, FMSUB, FMADD.
Not supporting any of the half-precision variant.
Got rid of the getFPOperandType function since it was redundant.
=> Added support for FMUL (by element) (scalar, single-precision and double-precision), FNMUL (scalar), FNMADD, FNMSUB, FMSUB, FMADD.

backend_tv/lifter.cpp, tests/arm-tv/vectors/saba/SABAv16i8.aarch64.ll, tests/arm-tv/vectors/saba/SABAv2i32.aarch64.ll, tests/arm-tv/vectors/saba/SABAv4i16.aarch64.ll, tests/arm-tv/vectors/saba/SABAv4i32.aarch64.ll, tests/arm-tv/vectors/saba/SABAv8i16.aarch64.ll, tests/arm-tv/vectors/saba/SABAv8i8.aarch64.ll, tests/arm-tv/vectors/uaba/UABAv8i16.aarch64.ll
Added support for `UABA`, `SABA`, `UABAL`, `UABAL2`, `SABAL`, and `SABAL2`
No tests for `UABAL`, `UABAL2`, `SABAL`, and `SABAL2` but the non-long versions have been tested and the non-accumulate versions have also been tested so confident about the implementations for these.
=> Added support for `UABA`, `SABA`, `UABAL`, `UABAL2`, `SABAL`, and `SABAL2`

backend_tv/lifter.cpp, tests/arm-tv/vectors/smaxp/SMAXPv2i32.aarch64.ll, tests/arm-tv/vectors/sminp/SMINPv2i32.aarch64.ll, tests/arm-tv/vectors/umaxp/UMAXPv2i32.aarch64.ll, tests/arm-tv/vectors/uminp/UMINPv2i32.aarch64.ll
Added support for `UMINP`, `UMAXP`, `SMINP`, `SMAXP`
Tested only the `v2i32` variants of these since the other 5 variants only had `NEON` intrinsic tests. But confident in implementation.
=> Added support for `UMINP`, `UMAXP`, `SMINP`, `SMAXP`

backend_tv/lifter.cpp, tests/arm-tv/vectors/sub/SUBv1i64.aarch64.ll
Complete support for `SUB (vector)` by adding missing variant `SUBv1i64`
=> Complete support for `SUB (vector)` by adding missing variant `SUBv1i64`

backend_tv/lifter.cpp, tests/arm-tv/misc/pointer-authentication/AUTIASP.aarch64.ll, tests/arm-tv/misc/pointer-authentication/AUTIBSP.aarch64.ll, tests/arm-tv/misc/pointer-authentication/PACIASP.aarch64.ll, tests/arm-tv/misc/pointer-authentication/PACIBSP.aarch64.ll
Added support for some pointer authentication instructions. They are just NO-OPS: `PACIA`, `PACIB`, `AUTIA`, `AUTIB`
=> Added support for `PACIA`, `PACIB`, `AUTIA`, `AUTIB`

backend_tv/lifter.cpp, tests/arm-tv/vectors/sshr/SSHRd.aarch64.ll, tests/arm-tv/vectors/usra/USRAd.aarch64.ll
Completed support for `USRA` and `SSHR` by adding the 1 element 64 bit variants
=> Completed support for `USRA` and `SSHR` by adding the 1 element 64 bit variants

backend_tv/lifter.cpp, tests/arm-tv/vectors/smull/SMULLv4i16_indexed.aarch64.ll
Bug Fix - `SMULL`, `UMULL`
Vector being indexed into was being truncated due to the instruction size sets and als usage of incorrect vector type was causing out of bounds access on certain instances.
=> Bug Fix - `SMULL`, `UMULL`

aslp-server.sh, backend_tv/aslp/README.md, build.sh
This is a simple in-memory cache in front of the aslp-server. It should speed things up considerably, assuming some opcodes are much more frequent than others.
=> aslp: add basic varnish cache

backend_tv/aslp/CMakeLists.txt, backend_tv/aslp/aslp_bridge.cpp, build.sh
we've moved around our repositories to separate the client/server code
from the main aslp repository.
possible breaking! this adds a new parameter to the aslp_connection
constructor. this will require a newer version of aslp-cpp.
if you are building with ./build.sh, deleting the build directory should
automatically fetch the correct version.
=> aslp: update references to aslp-server and aslp-cpp

backend_tv/aslp/aslp_bridge.cpp, backend_tv/aslp/aslp_bridge.h
=> Explicitly include std::variant

tests/arm-tv/ptrroundtrips/round-trip-test-0.aarch64.ll, tests/arm-tv/ptrroundtrips/round-trip-test-1.aarch64.ll, tests/arm-tv/ptrroundtrips/round-trip-test-2.aarch64.ll, tests/arm-tv/ptrroundtrips/round-trip-test-3.aarch64.ll, tests/arm-tv/ptrroundtrips/round-trip-test-4.aarch64.ll, tests/arm-tv/ptrroundtrips/round-trip-test-5.aarch64.ll, tests/arm-tv/ptrroundtrips/round-trip-test-6.aarch64.ll, tools/backend-tv.cpp
Replace instances of `ptrtoint`->`add`->`inttoptr` with a single `getelementptr`. Can prevent timeouts with alive.
=> Avoid pointer round trips

backend_tv/riscv2llvm_insns.cpp, tests/riscv-tv/extensions/f/fcvt_d_l.riscv.ll, tests/riscv-tv/extensions/f/fcvt_d_s.riscv.ll, tests/riscv-tv/extensions/f/fcvt_d_w.riscv.ll, tests/riscv-tv/extensions/f/fcvt_d_wu.riscv.ll, tests/riscv-tv/extensions/f/fcvt_lu_s.riscv.ll, tests/riscv-tv/extensions/f/fcvt_s_d.riscv.ll, tests/riscv-tv/extensions/f/fcvt_s_l.riscv.ll, tests/riscv-tv/extensions/f/fcvt_s_lu.riscv.ll, tests/riscv-tv/extensions/f/fcvt_w_s.riscv.ll, tests/riscv-tv/extensions/f/fld.riscv.ll, tests/riscv-tv/extensions/f/flw.riscv.ll, tests/riscv-tv/extensions/f/fmv_d_x.riscv.ll, tests/riscv-tv/extensions/f/fmv_w_x.riscv.ll, tests/riscv-tv/extensions/f/fmv_x_w.riscv.ll, tests/riscv-tv/extensions/f/fsd.riscv.ll, tests/riscv-tv/extensions/f/fsw.riscv.ll
Question: For narrowing conversion instructions, can we ignore the exception flags?
=> Add support for fp load/store/conversion

backend_tv/riscv2llvm.cpp, tests/riscv-tv/abi/double_pass_by_gpr.riscv.ll, tests/riscv-tv/abi/float_pass_by_gpr.riscv.ll
See https://github.com/riscv-non-isa/riscv-elf-psabi-doc/blob/master/riscv-cc.adoc:
> A real floating-point argument is passed in a floating-point argument register if it is no more than ABI_FLEN bits wide and at least one floating-point argument register is available. **Otherwise, it is passed according to the integer calling convention.** When a floating-point argument narrower than FLEN bits is passed in a floating-point register, it is 1-extended (NaN-boxed) to FLEN bits.
Fix the false positive riscv-tests/test-138151362.ll.
=> Fix argument passing with more than 8 fp values

backend_tv/mc2llvm.h, tests/riscv-tv/extensions/f/maximumnum.riscv.ll, tests/riscv-tv/extensions/f/minimumnum.riscv.ll
Just a typo. Slightly different semantics.
=> Lift to correct intrinsics for FMIN/FMAX
